src/controllers/account.ts
src/controllers/block.ts
src/interfaces/account.ts
src/models/account.ts
src/models/block.ts
src/routes/apiV1.ts
src/services/__mocks__/dataStore.ts
src/services/dataStore.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts

- Added new API routes to delete top level Pantry (account)
- Added new API route to delete individual Baskets (blocks)
- Added tests

Add ability to delete baskets / pantry

---

env.sample
package-lock.json
package.json
src/app/index.ts
src/app/scss/_topbar.scss
src/controllers/account.ts
src/services/__mocks__/mailer.ts
src/services/mailer.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts
tsconfig.json
yarn.lock

When a new account is created, send a welcome email with the pantry id
- Added new mailer service
- Added 2 new ENV vars
- Added new account email flow

Use SendGrid to send Welcome Email

---

.github/workflows/continuous_integration.yml
src/controllers/account.ts
src/services/logger.ts

- Adds logAndSlack helper function
- Adds Coveralls to project

Notify via slack when new accounts are created

---

src/controllers/account.ts
src/controllers/block.ts
src/interfaces/account.ts
src/models/account.ts
src/models/block.ts
src/services/__mocks__/dataStore.ts
src/services/dataStore.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts

- added scan() keys into dataStore
- replaced old get/set blocks logic with new logic to scan for keys matching an account pattern
- added tests

Refactoring how Accounts and Blocks are managed

---

src/controllers/account.ts
src/controllers/block.ts
src/models/account.ts
src/services/__mocks__/dataStore.ts
src/services/dataStore.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts

- Replaced `scan` with `keys` to return baskets
- Fixed log messages

Fixes Basket Retrieval 

---

src/controllers/account.ts
src/controllers/block.ts
src/models/account.ts
src/models/block.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts

- Fixes account/block TTL update when fetching blocks
- Updated tests
- Added block name to the deletion log
- DRY up tests

Fix Account & Block TTL Logic

---

index.html
src/app/scss/_variables.scss
src/app/templates/landingRight.html

- Added SEO meta tags
- Minor FE fixes

Adds SEO Meta Tags

---

src/app/templates/landingRight.html
src/controllers/account.ts
src/interfaces/account.ts
src/models/account.ts
src/models/block.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts

- Adds a percentage full indicator on the dashboard
- Updated landing page copy

Dashboard Updates

---

src/app/components/landingRight.ts
src/app/components/topbar.ts
src/app/scss/_app.scss
src/app/scss/_banner.scss
src/app/scss/_text.scss
src/app/scss/_variables.scss
src/app/scss/main.scss
src/app/templates/landingRight.html
src/app/templates/topbar.html
src/controllers/system.ts
src/interfaces/system.ts
src/interfaces/view.ts
src/main.ts
src/routes/systemV1.ts
src/services/__mocks__/dataStore.ts
src/services/dataStore.ts
tests/controllers/system.test.ts

- Adds a new API route + controller + tests for system status
- Adds a new page to the front end to display the status of Pantry

Add new route for system status

---

package-lock.json
src/controllers/account.ts
src/controllers/block.ts
src/controllers/system.ts
src/models/account.ts
src/models/block.ts
src/services/__mocks__/dataStore.ts
src/services/crm.ts
src/services/dataStore.ts
src/services/logger.ts
src/services/mailer.ts
tests/controllers/account.test.ts
tests/controllers/block.test.ts
tests/controllers/system.test.ts
yarn.lock

Instead of using Typescripts "catch all" `export = and import = require()` syntax, revert to a more traditional module based approach.

Refresh file import scheme

---

src/app/components/landingRight.ts
src/app/templates/landingRight.html

The front-end has been updated to only show the errors block if errors exist.

Fixed how the view logic shows/hides the error bar

---

client-libraries/Bash/README.md
client-libraries/Bash/pantry-client.bash

Just discovered your wonderful work. I needed a free and simple json store for my projects and getpantry.cloud turned out to be perfect. Made a client for myself. Thought others might find it useful. Hope you like it.

Added a Bash-client for Pantry API

---

.github/pull_request_template.md
.github/workflows/continuous_integration.yml
README.md

Pantry is picking up steam, and a few users have requsted information in how to
get the project running locally, an about contribution guidelines.
To make things easier, the following changes were made
* Added development setup instructions to README.md
* Added a pull request template
* Allow Actions to occure on every new pull request

Make Contributions Easier

---

src/main.ts

All "todo" lists and discussions should now be turned into Github issues going forward.
* Remove old todo list
Resolves #83

Remove Old ToDo List Items

---

index.html

Added add Google Tag Manager in index.html.
Will be able to add Google Analytics + other plugins to Pantry in future.
Resolves #**93**

Update index.html. Added Google Analytics + other plugins

---

src/app/templates/landingRight.html

The curl command on the page does not work on windows (altough curl is
installed on windows) so I added a native windows powershell command.
* 🐛 Fixed titles
changed from bold to h2 because it looks nicer
Resolves: #78 #98

:sparkles: Added powershell command

---

package-lock.json
package.json
src/services/environment.ts
src/services/logger.ts
tsconfig.json
yarn.lock

Let's publish our logs to Logflare to increase their visibility.
This change addresses the need by:
* Adding pino-logflare as a dependency
* Adding the pino-logflare plugin to Pino to push logs up to the cloud

Publish Logs to Logflare

---

src/app/components/sdk.ts

Update SDK list with new entry
* Added [pantry_wrapper](https://github.com/alexmulligan/pantry_wrapper) to the list of SDKs.

Update SDK list with new entry

---

src/app/components/sdk.ts

Added [pantry-nim](https://github.com/ire4ever1190/pantry-nim) library to sdk entries

Add pantry-nim to list

---

src/app/components/sdk.ts

Good day
this pull requests inserts my [JPantry](https://github.com/EnderCrypt/JPantry) library (for java) into sdk.ts

Add JPantry to sdk's

---

src/app/components/sdk.ts

Added [PHP ](https://github.com/sebaOfficial/pantry-cloud)Library pantry-cloud to SDK's

Added PHP Library pantry-cloud to SDK's

---

src/app/components/sdk.ts

Added the [pantry](https://pub.dev/packages/pantry) Dart package to the list of SDKs

Added Dart package to sdk.ts

---

src/app/components/sdk.ts

I am back with adding a new rust client for the pantry API.

Add Rust Client to list of SDK's
